//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaTradicional.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitaciones
    {
        public Habitaciones()
        {
            this.Reservas = new HashSet<Reservas>();
        }
    
        public int HabitacionID { get; set; }
        public string Hab_NumeroHabitacion { get; set; }
        public Nullable<int> Hab_Piso { get; set; }
        public string Hab_Estado { get; set; }
        public string Hab_NombreTipo { get; set; }
        public string Hab_DescripcionTipo { get; set; }
        public int Hab_Capacidad { get; set; }
        public decimal Hab_TarifaBase { get; set; }
    
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
