//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaTradicional.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBWEBHOTELV1 : DbContext
    {
        public DBWEBHOTELV1()
            : base("name=DBWEBHOTELV1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Habitaciones> Habitaciones { get; set; }
        public DbSet<Huespedes> Huespedes { get; set; }
        public DbSet<Reservas> Reservas { get; set; }
    }
}
