//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaTradicional.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int PagoID { get; set; }
        public int ReservaID { get; set; }
        public decimal Pag_Monto { get; set; }
        public Nullable<System.DateTime> Pag_FechaPago { get; set; }
        public string Pag_MetodoPago { get; set; }
        public string Pag_EstadoPago { get; set; }
    
        public virtual Reservas Reservas { get; set; }
    }
}
